version: "0.0.1"
services:
  redis-server:
    image: redis
    ports:
      - "6379:6379"

  backend:
    image: "sihookang47/spring-redis-example:latest"
    ports:
      - "80:8080"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis-server



